### PR TITLE
Kruskal

### PR DESCRIPTION
**Pull request by m-payal**

### CODE REVIEW

**Comment by shreyanshchordia** [comment]
The Kruskal folder that you have created, add a README.md file in that folder. And please describe the problem statement, or attach link to the problem statement.

**Comment by shreyanshchordia** [comment]
Once that is done I will merge the PR

**Comment by m-payal** [comment]
> The Kruskal folder that you have created, add a README.md file in that folder. And please describe the problem statement, or attach link to the problem statement.

Done

**Comment by shreyanshchordia** [comment]
README.md file is completely gibberish.

**Pull request closed without merging**
