### PR TITLE
number of islands.cpp

### PR DESCRIPTION
**Pull request by Ambareen09**

### CODE REVIEW

**Comment by shreyanshchordia** [comment]
Hey, the explanation in README.md looks a bit messy. Please format that part of the text and then mention me here once done. Then I will merge your PR.

**Comment by Ambareen09** [comment]
Ok sure I'll do that

**Comment by Ambareen09** [comment]
I've done the editing, kindly check it. 👍

**Comment by Ambareen09** [comment]
Please add my pull request label to "hacktoberfest-accepted" if you're happy with my contribution and merge it. :)

**Pull request merged**
